export const MENU_DEFINITIONS = [
  {
    id: 'file',
    label: 'File',
    items: [
      { id: 'file.new', label: 'New Text File', shortcut: 'Ctrl+N' },
      { id: 'file.newFilePrompt', label: 'New File...', shortcut: 'Ctrl+Alt+Win+N' },
      { id: 'file.newWindow', label: 'New Window', shortcut: 'Ctrl+Shift+N' },
      { id: 'file.newWindowProfile', label: 'New Window with Profile', submenu: [{ id: 'file.newProfile', label: 'New Profile...' }] },
      { type: 'separator' },
      { id: 'file.open', label: 'Open File...', shortcut: 'Ctrl+O' },
      { id: 'file.openFolder', label: 'Open Folder...', shortcut: 'Ctrl+Shift+K O' },
      { id: 'file.openWorkspace', label: 'Open Workspace from File...' },
      { id: 'file.openRecent', label: 'Open Recent', hasSubmenu: true },
      { type: 'separator' },
      { id: 'file.addFolderToWorkspace', label: 'Add Folder to Workspace...' },
      { id: 'file.saveWorkspaceAs', label: 'Save Workspace As...' },
      { id: 'file.duplicateWorkspace', label: 'Duplicate Workspace' },
      { type: 'separator' },
      { id: 'file.save', label: 'Save', shortcut: 'Ctrl+S' },
      { id: 'file.saveAs', label: 'Save As...', shortcut: 'Ctrl+Shift+S' },
      { id: 'file.saveAll', label: 'Save All', shortcut: 'Ctrl+Alt+K S' },
      { type: 'separator' },
      { id: 'file.share', label: 'Share', submenu: [
          { id: 'file.share.copyLink', label: 'Copy vscode.dev Link' },
          { id: 'file.share.exportProfile', label: 'Export Profile (Default)...' }
        ] 
      },
      { type: 'separator' },
      { id: 'file.autoSave', label: 'Auto Save', checkable: true },
      { id: 'file.preferences', label: 'Preferences', submenu: [
          { id: 'file.pref.profiles', label: 'Profiles', hasSubmenu: true },
          { id: 'settings.open', label: 'Settings', shortcut: 'Ctrl+,' },
          { id: 'view.openExtensions', label: 'Extensions', shortcut: 'Ctrl+Shift+X' },
          { id: 'settings.shortcuts', label: 'Keyboard Shortcuts', shortcut: 'Ctrl+K Ctrl+S' },
          { id: 'settings.snippets', label: 'Configure Snippets' },
          { id: 'settings.tasks', label: 'Tasks' },
          { id: 'settings.themes', label: 'Themes', hasSubmenu: true },
          { type: 'separator' },
          { id: 'settings.sync', label: 'Backup and Sync Settings...', disabled: true },
          { type: 'separator' },
          { id: 'settings.online', label: 'Online Services Settings' }
        ] 
      },
      { type: 'separator' },
      { id: 'file.revertFile', label: 'Revert File' },
      { id: 'file.closeEditor', label: 'Close Editor', shortcut: 'Ctrl+F4' },
      { id: 'file.closeFolder', label: 'Close Folder', shortcut: 'Ctrl+K F' },
      { id: 'file.closeWindow', label: 'Close Window', shortcut: 'Alt+F4' },
      { type: 'separator' },
      { id: 'file.exit', label: 'Exit' }
    ]
  },
  {
    id: 'edit',
    label: 'Edit',
    items: [
      { id: 'edit.undo', label: 'Undo', shortcut: 'Ctrl+Z' },
      { id: 'edit.redo', label: 'Redo', shortcut: 'Ctrl+Y' },
      { type: 'separator' },
      { id: 'edit.cut', label: 'Cut', shortcut: 'Ctrl+X' },
      { id: 'edit.copy', label: 'Copy', shortcut: 'Ctrl+C' },
      { id: 'edit.paste', label: 'Paste', shortcut: 'Ctrl+V' },
      { type: 'separator' },
      { id: 'edit.find', label: 'Find', shortcut: 'Ctrl+F' },
      { id: 'edit.replace', label: 'Replace', shortcut: 'Ctrl+H' },
      { type: 'separator' },
      { id: 'edit.findInFiles', label: 'Find in Files', shortcut: 'Ctrl+Shift+F' },
      { id: 'edit.replaceInFiles', label: 'Replace in Files', shortcut: 'Ctrl+Shift+H' },
      { type: 'separator' },
      { id: 'edit.toggleComment', label: 'Toggle Line Comment', shortcut: 'Ctrl+/' },
      { id: 'edit.toggleBlockComment', label: 'Toggle Block Comment', shortcut: 'Shift+Alt+A' },
      { id: 'edit.emmetExpand', label: 'Emmet: Expand Abbreviation', shortcut: 'Tab' }
    ]
  },
  {
    id: 'selection',
    label: 'Selection',
    items: [
      { id: 'selection.selectAll', label: 'Select All', shortcut: 'Ctrl+A' },
      { id: 'selection.expand', label: 'Expand Selection', shortcut: 'Shift+Alt+Right' },
      { id: 'selection.shrink', label: 'Shrink Selection', shortcut: 'Shift+Alt+Left' },
      { type: 'separator' },
      { id: 'selection.copyLineUp', label: 'Copy Line Up', shortcut: 'Shift+Alt+Up' },
      { id: 'selection.copyLineDown', label: 'Copy Line Down', shortcut: 'Shift+Alt+Down' },
      { id: 'selection.moveLineUp', label: 'Move Line Up', shortcut: 'Alt+Up' },
      { id: 'selection.moveLineDown', label: 'Move Line Down', shortcut: 'Alt+Down' },
      { id: 'selection.duplicateSelection', label: 'Duplicate Selection' },
      { type: 'separator' },
      { id: 'selection.addCursorAbove', label: 'Add Cursor Above', shortcut: 'Ctrl+Alt+Up' },
      { id: 'selection.addCursorBelow', label: 'Add Cursor Below', shortcut: 'Ctrl+Alt+Down' },
      { id: 'selection.addCursorsToLineEnds', label: 'Add Cursors to Line Ends', shortcut: 'Shift+Alt+I' },
      { id: 'selection.addNextOccurrence', label: 'Add Next Occurrence', shortcut: 'Ctrl+D' },
      { id: 'selection.addPreviousOccurrence', label: 'Add Previous Occurrence' },
      { id: 'selection.selectAllOccurrences', label: 'Select All Occurrences', shortcut: 'Ctrl+Shift+L' },
      { type: 'separator' },
      { id: 'selection.switchMultiCursor', label: 'Switch to Ctrl+Click for Multi-Cursor' },
      { id: 'selection.columnSelectionMode', label: 'Column Selection Mode', checkable: true }
    ]
  },
  {
    id: 'view',
    label: 'View',
    items: [
      { id: 'view.commandPalette', label: 'Command Palette...', shortcut: 'Ctrl+Shift+P' },
      { id: 'view.openView', label: 'Open View...' },
      { type: 'separator' },
      { 
        id: 'view.appearance', 
        label: 'Appearance', 
        hasSubmenu: true,
        submenu: [
          { id: 'view.appearance.fullScreen', label: 'Full Screen', shortcut: 'F11' },
          { id: 'view.appearance.zenMode', label: 'Zen Mode', shortcut: 'Ctrl+K Z' },
          { id: 'view.appearance.centeredLayout', label: 'Centered Layout' },
          { type: 'separator' },
          { id: 'view.appearance.menuBar', label: 'Menu Bar', checkable: true },
          { id: 'view.appearance.primarySidebar', label: 'Primary Side Bar', shortcut: 'Ctrl+B', checkable: true },
          { id: 'view.appearance.secondarySidebar', label: 'Secondary Side Bar', shortcut: 'Ctrl+Alt+B', checkable: true },
          { id: 'view.appearance.statusBar', label: 'Status Bar', checkable: true },
          { id: 'view.appearance.panel', label: 'Panel', shortcut: 'Ctrl+J', checkable: true },
          { type: 'separator' },
          { id: 'view.appearance.moveSidebarRight', label: 'Move Primary Side Bar Right' },
          { id: 'view.appearance.activityBarPos', label: 'Activity Bar Position', hasSubmenu: true },
          { id: 'view.appearance.panelPos', label: 'Panel Position', hasSubmenu: true },
          { id: 'view.appearance.alignPanel', label: 'Align Panel', hasSubmenu: true },
          { id: 'view.appearance.tabBar', label: 'Tab Bar', hasSubmenu: true },
          { id: 'view.appearance.editorActionsPos', label: 'Editor Actions Position', hasSubmenu: true },
          { type: 'separator' },
          { id: 'view.appearance.minimap', label: 'Minimap', checkable: true },
          { id: 'view.appearance.breadcrumbs', label: 'Breadcrumbs', checkable: true },
          { id: 'view.appearance.stickyScroll', label: 'Sticky Scroll' },
          { id: 'view.appearance.renderWhitespace', label: 'Render Whitespace', hasSubmenu: true },
          { id: 'view.appearance.renderControlChars', label: 'Render Control Characters', checkable: true },
          { type: 'separator' },
          { id: 'view.appearance.zoomIn', label: 'Zoom In', shortcut: 'Ctrl+=' },
          { id: 'view.appearance.zoomOut', label: 'Zoom Out', shortcut: 'Ctrl+-' },
          { id: 'view.appearance.resetZoom', label: 'Reset Zoom', shortcut: 'Ctrl+NumPad0' }
        ]
      },
      { 
        id: 'view.editorLayout', 
        label: 'Editor Layout', 
        hasSubmenu: true,
        submenu: [
          { id: 'view.layout.splitUp', label: 'Split Up', shortcut: 'Ctrl+K Ctrl+\\' },
          { id: 'view.layout.splitDown', label: 'Split Down' },
          { id: 'view.layout.splitLeft', label: 'Split Left' },
          { id: 'view.layout.splitRight', label: 'Split Right' },
          { type: 'separator' },
          { id: 'view.layout.splitInGroup', label: 'Split in Group', shortcut: 'Ctrl+K Ctrl+Shift+\\' },
          { type: 'separator' },
          { id: 'view.layout.moveEditorNewWindow', label: 'Move Editor into New Window' },
          { id: 'view.layout.copyEditorNewWindow', label: 'Copy Editor into New Window', shortcut: 'Ctrl+K O' },
          { type: 'separator' },
          { id: 'view.layout.single', label: 'Single' },
          { id: 'view.layout.twoCols', label: 'Two Columns' },
          { id: 'view.layout.threeCols', label: 'Three Columns' },
          { id: 'view.layout.twoRows', label: 'Two Rows' },
          { id: 'view.layout.threeRows', label: 'Three Rows' },
          { id: 'view.layout.grid', label: 'Grid (2x2)' },
          { id: 'view.layout.twoRowsRight', label: 'Two Rows Right' },
          { id: 'view.layout.twoColsBottom', label: 'Two Columns Bottom' },
          { type: 'separator' },
          { id: 'view.layout.flip', label: 'Flip Layout', shortcut: 'Shift+Alt+0' }
        ]
      },
      { type: 'separator' },
      { id: 'view.openExplorer', label: 'Explorer', shortcut: 'Ctrl+Shift+E' },
      { id: 'view.openSearch', label: 'Search', shortcut: 'Ctrl+Shift+F' },
      { id: 'view.openSourceControl', label: 'Source Control', shortcut: 'Ctrl+Shift+G' },
      { id: 'view.openRun', label: 'Run', shortcut: 'Ctrl+Shift+D' },
      { id: 'view.openExtensions', label: 'Extensions', shortcut: 'Ctrl+Shift+X' },
      { type: 'separator' },
      { id: 'view.aiChat', label: 'Chat', shortcut: 'Ctrl+Alt+I' },
      { id: 'view.browser', label: 'Browser', shortcut: 'Ctrl+Alt+/' },
      { type: 'separator' },
      { id: 'view.showProblems', label: 'Problems', shortcut: 'Ctrl+Shift+M' },
      { id: 'view.showOutput', label: 'Output', shortcut: 'Ctrl+Shift+U' },
      { id: 'view.showDebugConsole', label: 'Debug Console', shortcut: 'Ctrl+Shift+Y' },
      { id: 'view.showTerminal', label: 'Terminal', shortcut: 'Ctrl+`' },
      { type: 'separator' },
      { id: 'view.toggleWordWrap', label: 'Word Wrap', shortcut: 'Alt+Z', checkable: true }
    ]
  },
  {
    id: 'go',
    label: 'Go',
    items: [
      { id: 'go.back', label: 'Back', shortcut: 'Alt+Left' },
      { id: 'go.forward', label: 'Forward', shortcut: 'Alt+Right' },
      { id: 'go.lastEditLocation', label: 'Last Edit Location', shortcut: 'Ctrl+K Ctrl+Q' },
      { type: 'separator' },
      { 
        id: 'go.switchEditor', 
        label: 'Switch Editor', 
        hasSubmenu: true,
        submenu: [
          { id: 'go.switchEditor.next', label: 'Next Editor', shortcut: 'Ctrl+PageDown' },
          { id: 'go.switchEditor.prev', label: 'Previous Editor', shortcut: 'Ctrl+PageUp' },
          { type: 'separator' },
          { id: 'go.switchEditor.nextUsed', label: 'Next Used Editor' },
          { id: 'go.switchEditor.prevUsed', label: 'Previous Used Editor' },
          { type: 'separator' },
          { id: 'go.switchEditor.nextInGroup', label: 'Next Editor in Group', shortcut: 'Ctrl+K Ctrl+PageDown' },
          { id: 'go.switchEditor.prevInGroup', label: 'Previous Editor in Group', shortcut: 'Ctrl+K Ctrl+PageUp' },
          { type: 'separator' },
          { id: 'go.switchEditor.nextUsedInGroup', label: 'Next Used Editor in Group' },
          { id: 'go.switchEditor.prevUsedInGroup', label: 'Previous Used Editor in Group' }
        ]
      },
      { 
        id: 'go.switchGroup', 
        label: 'Switch Group', 
        hasSubmenu: true,
        submenu: [
          { id: 'go.switchGroup.next', label: 'Next Group' },
          { id: 'go.switchGroup.prev', label: 'Previous Group' },
          { type: 'separator' },
          { id: 'go.switchGroup.group1', label: 'Group 1', shortcut: 'Ctrl+1' },
          { id: 'go.switchGroup.group2', label: 'Group 2', shortcut: 'Ctrl+2' },
          { id: 'go.switchGroup.group3', label: 'Group 3', shortcut: 'Ctrl+3' }
        ]
      },
      { type: 'separator' },
      { id: 'go.file', label: 'Go to File...', shortcut: 'Ctrl+P' },
      { id: 'go.symbolInWorkspace', label: 'Go to Symbol in Workspace...', shortcut: 'Ctrl+T' },
      { type: 'separator' },
      { id: 'go.symbolInEditor', label: 'Go to Symbol in Editor...', shortcut: 'Ctrl+Shift+O' },
      { id: 'go.definition', label: 'Go to Definition', shortcut: 'F12' },
      { id: 'go.declaration', label: 'Go to Declaration' },
      { id: 'go.typeDefinition', label: 'Go to Type Definition' },
      { id: 'go.implementations', label: 'Go to Implementations', shortcut: 'Ctrl+F12' },
      { id: 'go.references', label: 'Go to References', shortcut: 'Shift+F12' },
      { type: 'separator' },
      { id: 'go.line', label: 'Go to Line/Column...', shortcut: 'Ctrl+G' },
      { id: 'go.bracket', label: 'Go to Bracket', shortcut: 'Ctrl+Shift+\\' },
      { type: 'separator' },
      { id: 'go.nextProblem', label: 'Next Problem', shortcut: 'F8' },
      { id: 'go.prevProblem', label: 'Previous Problem', shortcut: 'Shift+F8' },
      { type: 'separator' },
      { id: 'go.nextChange', label: 'Next Change', shortcut: 'Alt+F3' },
      { id: 'go.prevChange', label: 'Previous Change', shortcut: 'Shift+Alt+F3' }
    ]
  },
  {
    id: 'run',
    label: 'Run',
    items: [
      { id: 'run.debug', label: 'Start Debugging', shortcut: 'F5' },
      { id: 'run.noDebug', label: 'Run Without Debugging', shortcut: 'Ctrl+F5' },
      { id: 'run.stopDebug', label: 'Stop Debugging', shortcut: 'Shift+F5' },
      { id: 'run.restartDebug', label: 'Restart Debugging', shortcut: 'Ctrl+Shift+F5' },
      { type: 'separator' },
      { id: 'run.openConfigs', label: 'Open Configurations' },
      { id: 'run.addConfig', label: 'Add Configuration...' },
      { type: 'separator' },
      { id: 'run.stepOver', label: 'Step Over', shortcut: 'F10' },
      { id: 'run.stepInto', label: 'Step Into', shortcut: 'F11' },
      { id: 'run.stepOut', label: 'Step Out', shortcut: 'Shift+F11' },
      { id: 'run.continue', label: 'Continue', shortcut: 'F5' },
      { type: 'separator' },
      { id: 'run.breakpoint', label: 'Toggle Breakpoint', shortcut: 'F9' },
      { id: 'run.newBreakpoint', label: 'New Breakpoint', hasSubmenu: true },
      { type: 'separator' },
      { id: 'run.enableAllBreakpoints', label: 'Enable All Breakpoints' },
      { id: 'run.disableAllBreakpoints', label: 'Disable All Breakpoints' },
      { id: 'run.removeAllBreakpoints', label: 'Remove All Breakpoints' },
      { type: 'separator' },
      { id: 'run.installDebuggers', label: 'Install Additional Debuggers...' }
    ]
  },
  {
    id: 'terminal',
    label: 'Terminal',
    items: [
      { id: 'terminal.new', label: 'New Terminal', shortcut: 'Ctrl+Shift+`' },
      { id: 'terminal.split', label: 'Split Terminal', shortcut: 'Ctrl+Shift+5' },
      { id: 'terminal.newWindow', label: 'New Terminal Window', shortcut: 'Ctrl+Shift+Alt+`' },
      { type: 'separator' },
      { id: 'terminal.runTask', label: 'Run Task...' },
      { id: 'terminal.runBuildTask', label: 'Run Build Task...', shortcut: 'Ctrl+Shift+B' },
      { id: 'terminal.runActiveFile', label: 'Run Active File' },
      { id: 'terminal.runSelectedText', label: 'Run Selected Text' },
      { type: 'separator' },
      { id: 'terminal.showRunningTasks', label: 'Show Running Tasks...' },
      { id: 'terminal.restartTask', label: 'Restart Running Task...' },
      { id: 'terminal.terminateTask', label: 'Terminate Task...' },
      { type: 'separator' },
      { id: 'terminal.configureTasks', label: 'Configure Tasks...' },
      { id: 'terminal.configureBuildTask', label: 'Configure Default Build Task...' }
    ]
  },
  {
    id: 'help',
    label: 'Help',
    items: [
      { id: 'help.welcome', label: 'Welcome' },
      { id: 'help.showAllCommands', label: 'Show All Commands', shortcut: 'Ctrl+Shift+P' },
      { id: 'help.documentation', label: 'Documentation' },
      { id: 'help.editorPlayground', label: 'Editor Playground' },
      { id: 'help.openWalkthrough', label: 'Open Walkthrough...' },
      { id: 'help.releaseNotes', label: 'Show Release Notes' },
      { id: 'help.accessibility', label: 'Get Started with Accessibility Features' },
      { id: 'help.askVSCode', label: 'Ask @vscode' },
      { type: 'separator' },
      { id: 'help.shortcutReference', label: 'Keyboard Shortcuts Reference', shortcut: 'Ctrl+K Ctrl+R' },
      { id: 'help.videoTutorials', label: 'Video Tutorials' },
      { id: 'help.tipsAndTricks', label: 'Tips and Tricks' },
      { type: 'separator' },
      { id: 'help.youtube', label: 'Join Us on YouTube' },
      { id: 'help.featureRequests', label: 'Search Feature Requests' },
      { id: 'help.reportIssue', label: 'Report Issue' },
      { type: 'separator' },
      { id: 'help.viewLicense', label: 'View License' },
      { id: 'help.privacyStatement', label: 'Privacy Statement' },
      { type: 'separator' },
      { id: 'help.toggleDevTools', label: 'Toggle Developer Tools' },
      { id: 'help.openProcessExplorer', label: 'Open Process Explorer' },
      { type: 'separator' },
      { id: 'help.checkForUpdates', label: 'Check for Updates...' },
      { type: 'separator' },
      { id: 'help.about', label: 'About' }
    ]
  }
];

export const FALLBACK_WORKSPACE_FILES = [
  'src/App.jsx',
  'src/main.jsx',
  'src/index.css',
  'src/features/editor/EditorPanel.jsx',
  'src/features/files/FilePanel.jsx',
  'src/features/ai/AIPanel.jsx',
  'src/features/terminal/TerminalComponent.jsx',
  'electron/main.cjs',
  'electron/preload.cjs',
  'docs/CODEBASE_STRUCTURE.md',
  'docs/STRICT_ENGINEERING_RULES.md',
  'README.md',
  'package.json',
  'vite.config.js'
];
